import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.jobs': 'Jobs',
    'nav.customers': 'Customers',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.users': 'Users',
    'nav.activity': 'Activity',
    'nav.logout': 'Logout',
    'nav.logoutConfirm': 'Are you sure you want to logout?',
    
    // Login Page
    'login.title': 'Inventory Manager',
    'login.subtitle': 'Family Business Portal',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signin': 'Sign In',
    'login.signingin': 'Signing in...',
    'login.hint': 'Default login: admin / admin123',
    'login.enterUsername': 'Enter username',
    'login.enterPassword': 'Enter password',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalItems': 'Total Items',
    'dashboard.tireShopValue': 'Tire Shop Value',
    'dashboard.bodyShopValue': 'Body Shop Value',
    'dashboard.activeJobs': 'Active Jobs',
    'dashboard.currentInventoryValue': 'Current inventory value',
    'dashboard.lowStockAlert': 'Low Stock Alert - Tire Shop',
    'dashboard.items': 'items',
    'dashboard.allStockedUp': 'All Stocked Up!',
    'dashboard.allStockedUpDesc': 'All Tire Shop items are well stocked. Great job keeping inventory levels healthy!',
    'dashboard.itemName': 'Item Name',
    'dashboard.currentStock': 'Current Stock',
    'dashboard.status': 'Status',
    'dashboard.units': 'units',
    'dashboard.critical': 'Critical',
    'dashboard.warning': 'Warning',
    'dashboard.low': 'Low',
    'dashboard.moreItemsBelowThreshold': 'more items below stock threshold',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.importExcel': 'Import Excel',
    'inventory.addItem': 'Add Item',
    'inventory.mainShop': 'Main Shop Inventory',
    'inventory.tireShop': 'Tire Shop Inventory',
    'inventory.searchPlaceholder': 'Search by name, category, or supplier...',
    'inventory.name': 'Name',
    'inventory.category': 'Category',
    'inventory.quantity': 'Quantity',
    'inventory.unitPrice': 'Unit Price',
    'inventory.supplier': 'Supplier',
    'inventory.location': 'Location',
    'inventory.actions': 'Actions',
    'inventory.noItemsInSection': 'No items in {{section}} yet',
    'inventory.noItemsFound': 'No items found matching your search',
    'inventory.addNewItemTo': 'Add New Item to {{section}}',
    'inventory.editItem': 'Edit Item',
    'inventory.description': 'Description',
    'inventory.section': 'Section',
    'inventory.updateItem': 'Update Item',
    'inventory.importFromExcel': 'Import from Excel',
    'inventory.uploadExcelFile': 'Upload an Excel file (.xlsx, .xls) or CSV file with your inventory data.',
    'inventory.requiredColumns': 'Required columns: Item Name, Quantity, Unit Price',
    'inventory.beingEditedBy': 'Being edited by {{user}}',
    'inventory.realtimeActive': 'Real-time updates active',
    'inventory.offline': 'Offline - changes will sync when reconnected',
    'inventory.uncategorized': 'Uncategorized',
    'inventory.itemAddedSuccess': 'Item added successfully!',
    'inventory.itemUpdatedSuccess': 'Item updated successfully!',
    'inventory.itemDeletedSuccess': 'Item deleted successfully!',
    'inventory.errorLoadingItems': 'Failed to load inventory items',
    'inventory.errorAddingItem': 'Failed to add item',
    'inventory.errorUpdatingItem': 'Failed to update item',
    'inventory.errorDeletingItem': 'Failed to delete item',
    'inventory.errorImporting': 'Failed to import file',
    'inventory.deleteConfirm': 'Are you sure you want to delete "{{name}}"?',
    'inventory.importSuccess': 'Import completed! Successful: {{successful}}, Failed: {{failed}}',
    
    // Jobs
    'jobs.title': 'Jobs Management',
    'jobs.createJob': 'Create Job',
    'jobs.currentJobs': 'Current Jobs',
    'jobs.completedJobs': 'Completed Jobs',
    'jobs.noCurrentJobs': 'No current jobs',
    'jobs.noCompletedJobs': 'No completed jobs',
    'jobs.customer': 'Customer',
    'jobs.contact': 'Contact',
    'jobs.startDate': 'Start Date',
    'jobs.totalCost': 'Total Cost',
    'jobs.viewDetails': 'View Details',
    'jobs.delete': 'Delete',
    'jobs.createNew': 'Create New Job',
    'jobs.jobName': 'Job Name',
    'jobs.customerName': 'Customer Name',
    'jobs.customerContact': 'Customer Contact',
    'jobs.description': 'Description',
    'jobs.jobPlaceholder': 'e.g., BMW 5 Series Repair',
    'jobs.descriptionPlaceholder': 'Job details and requirements...',
    'jobs.create': 'Create Job',
    'jobs.jobInformation': 'Job Information',
    'jobs.status': 'Status',
    'jobs.active': 'Active',
    'jobs.completed': 'Completed',
    'jobs.cancelled': 'Cancelled',
    'jobs.partsUsed': 'Parts Used',
    'jobs.addParts': 'Add Parts',
    'jobs.noPartsAssigned': 'No parts assigned to this job yet',
    'jobs.documents': 'Documents & Images',
    'jobs.uploadFile': 'Upload File',
    'jobs.noFilesUploaded': 'No files uploaded yet',
    'jobs.markCompleted': 'Mark as Completed',
    'jobs.cancelJob': 'Cancel Job',
    'jobs.reopenJob': 'Reopen Job',
    'jobs.deleteJob': 'Delete Job',
    'jobs.addPartToJob': 'Add Part to Job',
    'jobs.selectInventorySection': 'Select Inventory Section',
    'jobs.bodyShopParts': 'Body Shop Parts',
    'jobs.tireShopParts': 'Tire Shop Parts',
    'jobs.selectPartFrom': 'Select Part from {{section}}',
    'jobs.choosePart': 'Choose a part...',
    'jobs.noPartsAvailable': 'No parts available in {{section}}',
    'jobs.showing': 'Showing',
    'jobs.partsFrom': 'parts from',
    'jobs.addPart': 'Add Part',
    'jobs.removePart': 'Remove this part from the job?',
    'jobs.deleteJobConfirm': 'Are you sure you want to delete {{name}}?',
    'jobs.cannotUndo': 'This action cannot be undone.',
    'jobs.inStock': 'in stock',
    
    // Customers
    'customers.title': 'Customers',
    'customers.addCustomer': 'Add Customer',
    'customers.searchPlaceholder': 'Search customers by name, email, or phone...',
    'customers.noCustomers': 'No customers found',
    'customers.jobs': 'jobs',
    'customers.phone': 'Phone',
    'customers.email': 'Email',
    'customers.address': 'Address',
    'customers.edit': 'Edit',
    'customers.delete': 'Delete',
    'customers.addNew': 'Add New Customer',
    'customers.editCustomer': 'Edit Customer',
    'customers.name': 'Name',
    'customers.city': 'City',
    'customers.state': 'State',
    'customers.zip': 'ZIP',
    'customers.notes': 'Notes',
    'customers.add': 'Add Customer',
    'customers.update': 'Update Customer',
    'customers.deleteConfirm': 'Are you sure you want to delete {{name}}?',
    
    // Analytics
    'analytics.title': 'Analytics & Insights',
    'analytics.subtitle': 'Track your business performance and trends over time',
    'analytics.totalInventoryValue': 'Total Inventory Value',
    'analytics.completedJobs': 'Completed Jobs',
    'analytics.avgJobValue': 'Avg. Job Value',
    'analytics.fromLastMonth': 'from last month',
    'analytics.basedOnCompleted': 'Based on completed jobs',
    'analytics.inventoryTrend': 'Inventory Value Trend',
    'analytics.inventoryTrendDesc': 'Total inventory value over the last 6 months',
    'analytics.jobsCompleted': 'Jobs Completed',
    'analytics.jobsCompletedDesc': 'Monthly job completion rate',
    'analytics.mostUsedParts': 'Most Used Parts',
    'analytics.mostUsedPartsDesc': 'Top parts by usage across all jobs',
    'analytics.noPartsData': 'No parts data available yet. Complete some jobs to see popular parts.',
    
    // Reports
    'reports.title': 'Reports',
    
    // Users
    'users.title': 'User Management',
    'users.addUser': 'Add New User',
    'users.username': 'Username',
    'users.fullName': 'Full Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.lastLogin': 'Last Login',
    'users.status': 'Status',
    'users.actions': 'Actions',
    'users.changePassword': 'Change Password',
    'users.deactivate': 'Deactivate',
    'users.activate': 'Activate',
    'users.admin': 'Admin',
    'users.user': 'User',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.never': 'Never',
    'users.noUsers': 'No users found',
    'users.password': 'Password',
    'users.newPassword': 'New Password',
    'users.create': 'Create User',
    'users.changePasswordFor': 'Change Password for {{username}}',
    
    // Activity Logs
    'activity.title': 'Activity Logs',
    
    // Common
    'common.loading': 'Loading...',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.inventory': 'Inventario',
    'nav.jobs': 'Trabajos',
    'nav.customers': 'Clientes',
    'nav.analytics': 'Análisis',
    'nav.reports': 'Informes',
    'nav.users': 'Usuarios',
    'nav.activity': 'Actividad',
    'nav.logout': 'Cerrar Sesión',
    'nav.logoutConfirm': '¿Está seguro de que desea cerrar sesión?',
    
    // Login Page
    'login.title': 'Gestor de Inventario',
    'login.subtitle': 'Portal de Negocio Familiar',
    'login.username': 'Usuario',
    'login.password': 'Contraseña',
    'login.signin': 'Iniciar Sesión',
    'login.signingin': 'Iniciando sesión...',
    'login.hint': 'Usuario predeterminado: admin / admin123',
    'login.enterUsername': 'Ingrese usuario',
    'login.enterPassword': 'Ingrese contraseña',
    
    // Dashboard
    'dashboard.title': 'Panel Principal',
    'dashboard.totalItems': 'Total de Artículos',
    'dashboard.tireShopValue': 'Valor Tienda de Llantas',
    'dashboard.bodyShopValue': 'Valor Taller de Carrocería',
    'dashboard.activeJobs': 'Trabajos Activos',
    'dashboard.currentInventoryValue': 'Valor actual del inventario',
    'dashboard.lowStockAlert': 'Alerta de Stock Bajo - Tienda de Llantas',
    'dashboard.items': 'artículos',
    'dashboard.allStockedUp': '¡Todo Abastecido!',
    'dashboard.allStockedUpDesc': 'Todos los artículos de la tienda de llantas están bien abastecidos. ¡Buen trabajo manteniendo niveles de inventario saludables!',
    'dashboard.itemName': 'Nombre del Artículo',
    'dashboard.currentStock': 'Stock Actual',
    'dashboard.status': 'Estado',
    'dashboard.units': 'unidades',
    'dashboard.critical': 'Crítico',
    'dashboard.warning': 'Advertencia',
    'dashboard.low': 'Bajo',
    'dashboard.moreItemsBelowThreshold': 'artículos más por debajo del umbral de stock',
    
    // Inventory
    'inventory.title': 'Gestión de Inventario',
    'inventory.importExcel': 'Importar Excel',
    'inventory.addItem': 'Agregar Artículo',
    'inventory.mainShop': 'Inventario Taller Principal',
    'inventory.tireShop': 'Inventario Tienda de Llantas',
    'inventory.searchPlaceholder': 'Buscar por nombre, categoría o proveedor...',
    'inventory.name': 'Nombre',
    'inventory.category': 'Categoría',
    'inventory.quantity': 'Cantidad',
    'inventory.unitPrice': 'Precio Unitario',
    'inventory.supplier': 'Proveedor',
    'inventory.location': 'Ubicación',
    'inventory.actions': 'Acciones',
    'inventory.noItemsInSection': 'No hay artículos en {{section}} todavía',
    'inventory.noItemsFound': 'No se encontraron artículos que coincidan con su búsqueda',
    'inventory.addNewItemTo': 'Agregar Nuevo Artículo a {{section}}',
    'inventory.editItem': 'Editar Artículo',
    'inventory.description': 'Descripción',
    'inventory.section': 'Sección',
    'inventory.updateItem': 'Actualizar Artículo',
    'inventory.importFromExcel': 'Importar desde Excel',
    'inventory.uploadExcelFile': 'Cargue un archivo Excel (.xlsx, .xls) o CSV con sus datos de inventario.',
    'inventory.requiredColumns': 'Columnas requeridas: Nombre del Artículo, Cantidad, Precio Unitario',
    'inventory.beingEditedBy': 'Siendo editado por {{user}}',
    'inventory.realtimeActive': 'Actualizaciones en tiempo real activas',
    'inventory.offline': 'Sin conexión - los cambios se sincronizarán cuando se reconecte',
    'inventory.uncategorized': 'Sin Categoría',
    'inventory.itemAddedSuccess': '¡Artículo agregado exitosamente!',
    'inventory.itemUpdatedSuccess': '¡Artículo actualizado exitosamente!',
    'inventory.itemDeletedSuccess': '¡Artículo eliminado exitosamente!',
    'inventory.errorLoadingItems': 'Error al cargar artículos del inventario',
    'inventory.errorAddingItem': 'Error al agregar artículo',
    'inventory.errorUpdatingItem': 'Error al actualizar artículo',
    'inventory.errorDeletingItem': 'Error al eliminar artículo',
    'inventory.errorImporting': 'Error al importar archivo',
    'inventory.deleteConfirm': '¿Está seguro de que desea eliminar "{{name}}"?',
    'inventory.importSuccess': '¡Importación completada! Exitosos: {{successful}}, Fallidos: {{failed}}',
    
    // Jobs
    'jobs.title': 'Gestión de Trabajos',
    'jobs.createJob': 'Crear Trabajo',
    'jobs.currentJobs': 'Trabajos Actuales',
    'jobs.completedJobs': 'Trabajos Completados',
    'jobs.noCurrentJobs': 'No hay trabajos actuales',
    'jobs.noCompletedJobs': 'No hay trabajos completados',
    'jobs.customer': 'Cliente',
    'jobs.contact': 'Contacto',
    'jobs.startDate': 'Fecha de Inicio',
    'jobs.totalCost': 'Costo Total',
    'jobs.viewDetails': 'Ver Detalles',
    'jobs.delete': 'Eliminar',
    'jobs.createNew': 'Crear Nuevo Trabajo',
    'jobs.jobName': 'Nombre del Trabajo',
    'jobs.customerName': 'Nombre del Cliente',
    'jobs.customerContact': 'Contacto del Cliente',
    'jobs.description': 'Descripción',
    'jobs.jobPlaceholder': 'ej., Reparación BMW Serie 5',
    'jobs.descriptionPlaceholder': 'Detalles y requisitos del trabajo...',
    'jobs.create': 'Crear Trabajo',
    'jobs.jobInformation': 'Información del Trabajo',
    'jobs.status': 'Estado',
    'jobs.active': 'Activo',
    'jobs.completed': 'Completado',
    'jobs.cancelled': 'Cancelado',
    'jobs.partsUsed': 'Partes Utilizadas',
    'jobs.addParts': 'Agregar Partes',
    'jobs.noPartsAssigned': 'No hay partes asignadas a este trabajo todavía',
    'jobs.documents': 'Documentos e Imágenes',
    'jobs.uploadFile': 'Subir Archivo',
    'jobs.noFilesUploaded': 'No hay archivos subidos todavía',
    'jobs.markCompleted': 'Marcar como Completado',
    'jobs.cancelJob': 'Cancelar Trabajo',
    'jobs.reopenJob': 'Reabrir Trabajo',
    'jobs.deleteJob': 'Eliminar Trabajo',
    'jobs.addPartToJob': 'Agregar Parte al Trabajo',
    'jobs.selectInventorySection': 'Seleccionar Sección de Inventario',
    'jobs.bodyShopParts': 'Partes de Carrocería',
    'jobs.tireShopParts': 'Partes de Llantas',
    'jobs.selectPartFrom': 'Seleccionar parte de {{section}}',
    'jobs.choosePart': 'Elegir una parte...',
    'jobs.noPartsAvailable': 'No hay partes disponibles en {{section}}',
    'jobs.showing': 'Mostrando',
    'jobs.partsFrom': 'partes de',
    'jobs.addPart': 'Agregar Parte',
    'jobs.removePart': '¿Eliminar esta parte del trabajo?',
    'jobs.deleteJobConfirm': '¿Está seguro de que desea eliminar {{name}}?',
    'jobs.cannotUndo': 'Esta acción no se puede deshacer.',
    'jobs.inStock': 'en stock',
    
    // Customers
    'customers.title': 'Clientes',
    'customers.addCustomer': 'Agregar Cliente',
    'customers.searchPlaceholder': 'Buscar clientes por nombre, email o teléfono...',
    'customers.noCustomers': 'No se encontraron clientes',
    'customers.jobs': 'trabajos',
    'customers.phone': 'Teléfono',
    'customers.email': 'Email',
    'customers.address': 'Dirección',
    'customers.edit': 'Editar',
    'customers.delete': 'Eliminar',
    'customers.addNew': 'Agregar Nuevo Cliente',
    'customers.editCustomer': 'Editar Cliente',
    'customers.name': 'Nombre',
    'customers.city': 'Ciudad',
    'customers.state': 'Estado',
    'customers.zip': 'Código Postal',
    'customers.notes': 'Notas',
    'customers.add': 'Agregar Cliente',
    'customers.update': 'Actualizar Cliente',
    'customers.deleteConfirm': '¿Está seguro de que desea eliminar {{name}}?',
    
    // Analytics
    'analytics.title': 'Análisis e Información',
    'analytics.subtitle': 'Rastree el rendimiento y las tendencias de su negocio a lo largo del tiempo',
    'analytics.totalInventoryValue': 'Valor Total del Inventario',
    'analytics.completedJobs': 'Trabajos Completados',
    'analytics.avgJobValue': 'Valor Promedio del Trabajo',
    'analytics.fromLastMonth': 'del mes pasado',
    'analytics.basedOnCompleted': 'Basado en trabajos completados',
    'analytics.inventoryTrend': 'Tendencia del Valor del Inventario',
    'analytics.inventoryTrendDesc': 'Valor total del inventario durante los últimos 6 meses',
    'analytics.jobsCompleted': 'Trabajos Completados',
    'analytics.jobsCompletedDesc': 'Tasa de finalización mensual de trabajos',
    'analytics.mostUsedParts': 'Partes Más Utilizadas',
    'analytics.mostUsedPartsDesc': 'Principales partes por uso en todos los trabajos',
    'analytics.noPartsData': 'Aún no hay datos de partes disponibles. Complete algunos trabajos para ver las partes populares.',
    
    // Reports
    'reports.title': 'Informes',
    
    // Users
    'users.title': 'Gestión de Usuarios',
    'users.addUser': 'Agregar Nuevo Usuario',
    'users.username': 'Usuario',
    'users.fullName': 'Nombre Completo',
    'users.email': 'Email',
    'users.role': 'Rol',
    'users.lastLogin': 'Último Acceso',
    'users.status': 'Estado',
    'users.actions': 'Acciones',
    'users.changePassword': 'Cambiar Contraseña',
    'users.deactivate': 'Desactivar',
    'users.activate': 'Activar',
    'users.admin': 'Administrador',
    'users.user': 'Usuario',
    'users.active': 'Activo',
    'users.inactive': 'Inactivo',
    'users.never': 'Nunca',
    'users.noUsers': 'No se encontraron usuarios',
    'users.password': 'Contraseña',
    'users.newPassword': 'Nueva Contraseña',
    'users.create': 'Crear Usuario',
    'users.changePasswordFor': 'Cambiar Contraseña para {{username}}',
    
    // Activity Logs
    'activity.title': 'Registros de Actividad',
    
    // Common
    'common.loading': 'Cargando...',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.upload': 'Subir',
    'common.download': 'Descargar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.required': 'Requerido',
    'common.optional': 'Opcional',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
  }
};

export const LanguageProvider = ({ children }) => {
  // Get initial language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'es' : 'en');
  };

  // Translation function with simple template string replacement
  const t = (key, replacements = {}) => {
    let translation = translations[language][key] || key;
    
    // Replace {{variable}} placeholders with actual values
    Object.keys(replacements).forEach(replaceKey => {
      const placeholder = `{{${replaceKey}}}`;
      translation = translation.replace(placeholder, replacements[replaceKey]);
    });
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
